apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prometheus-networkpolicy
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from Grafana to query metrics
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
      ports:
        - protocol: TCP
          port: 9090
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow scraping application metrics in dev namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infervoyage-dev
          podSelector:
            matchLabels:
              app: api
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infervoyage-dev
          podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 9187
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infervoyage-dev
          podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 9121
    # Allow scraping local metrics endpoints in monitoring namespace
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus-node-exporter
      ports:
        - protocol: TCP
          port: 9100
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kube-state-metrics
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: alertmanager
      ports:
        - protocol: TCP
          port: 9093
    # Allow querying Kubernetes API Server for Service Discovery
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
