apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: infervoyage-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  namespace: infervoyage-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  namespace: infervoyage-dev
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
