apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infervoyage.ollama.fullname" . }}-pvc
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
    component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.storageSize }}
  storageClassName: {{ .Values.ollama.storageClass }}
