apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infervoyage.postgres.fullname" . }}-pvc
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
  storageClassName: {{ .Values.postgres.storageClass }}
