apiVersion: v1
kind: Service
metadata:
  name: {{ include "infervoyage.redis.fullname" . }}
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
    component: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
    - name: metrics
      port: 9121
      targetPort: metrics
  selector:
    {{- include "infervoyage.selectorLabels" . | nindent 4 }}
    component: redis
  type: ClusterIP
