apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infervoyage.redis.fullname" . }}-config
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
    component: redis
data:
  redis.conf: |
    maxmemory {{ .Values.redis.maxmemory }}
    maxmemory-policy {{ .Values.redis.maxmemoryPolicy }}
    save ""
    appendonly no
