apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infervoyage.fullname" . }}-secrets
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-db: {{ .Values.postgres.db | b64enc | quote }}
  api-secret-key: {{ .Values.api.secretKey | b64enc | quote }}
