apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infervoyage.fullname" . }}-secrets
  labels:
    {{- include "infervoyage.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-db: {{ .Values.postgres.db | b64enc | quote }}
  api-secret-key: {{ .Values.api.secretKey | b64enc | quote }}
  smtp-host: {{ .Values.api.mail.server | b64enc | quote }}
  smtp-port: {{ .Values.api.mail.port | b64enc | quote }}
  smtp-user: {{ .Values.api.mail.user | default "" | b64enc | quote }}
  smtp-password: {{ .Values.api.mail.password | default "" | b64enc | quote }}
  resend-api-key: {{ .Values.api.mail.resendApiKey | default "" | b64enc | quote }}
  resend-sender: {{ .Values.api.mail.from | default "onboarding@resend.dev" | b64enc | quote }}
